repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [ "--force-exclude=bastionai" ]
        exclude: bastionai/
    -   id: black-jupyter
        args: [ "--force-exclude=bastionai" ]
        exclude: bastionai/
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: [ '--manifest-path=./server/Cargo.toml', '--' ]
        exclude: bastionai/
