site_name: "BastionAI"

site_url: https://www.mithrilsecurity.io/

repo_url: https://github.com/mithril-security/bastionai

theme:
  name: material
  custom_dir: docs/material_theme_customization
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
    - scheme: default
      toggle:
        icon: material/weather-night

extra:
  homepage: https://mithrilsecurity.io

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
- search
- mkdocs-jupyter
- glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes: 
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom

nav:
  - "Documentation":
    - "What is BastionAI": "docs/What_is_BastionAI.md"
    - "Examples":
      - "docs/examples/resnet_example_notebook.ipynb"
      - "docs/examples/distilbert_example_notebook.ipynb"
    - "Main Concepts":
      - "Overview": "docs/main_concepts/overview.md"
      - "Remote Training": "docs/main_concepts/remote_training.md"
      - "Data Privacy": "docs/main_concepts/data_privacy.md"
    - "Interoperability": "docs/lib_interop.md"
    - "Deployment":
      - "On-premise" : "docs/deployment/on_premise.md"
    - "Contributing":
      - "Contributing": "docs/contributing/CONTRIBUTING.md"
      - "Code of Conduct": "docs/contributing/Code_of_Conduct.md"
    - "FAQ": "docs/FAQ.md"
  - "Getting Started":
      - "Quick Start": "getting-started/quick-start.md"
  - "API reference": "resources/bastionai/client.html"
  - "Benchmarks": 
    - "AMD EPYC 773 CPU" : 'benchmarking/bench-amd-epyc-7763.md'
    - "Nvidia V100 and A100 GPUs" : 'benchmarking/bench-nvidia-a100-v100.md'