site_name: BastionLab

site_url: https://www.mithrilsecurity.io/

repo_url: https://github.com/mithril-security/bastionlab

theme:
  name: material
  custom_dir: docs/material_theme_customization
  features:
    - navigation.instant
    - search.highlight
    - content.tabs.link
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
    - scheme: default
      toggle:
        icon: material/weather-night

extra:
  homepage: https://mithrilsecurity.io

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- mkdocs-jupyter

nav:
- Home: 'index.md'
- Quick Tour: 'docs/quick-tour/quick-tour.ipynb'
- Tutorials:
  - Installation: 'docs/tutorials/installation.md'
  - Data visualization: 'docs/tutorials/visualization.ipynb'
  - Data cleaning: 'docs/tutorials/data_cleaning.ipynb'
  - Authentication: 'docs/tutorials/authentication.ipynb'
  - Combining datasets: 'docs/tutorials/combining_datasets.ipynb'
- How-to-Guides:
  - Covid-19 cleaning and exploration: 'docs/use-cases/covid_use_case.ipynb'
- Concepts:
  - Remote Data Science: 'docs/concept-guides/remote_data_science.md'
- "API Reference": "docs/resources/bastionlab/index.html"
- Torch:
  - 'docs/torch/overview.md'
- Security: 'docs/concept-guides/threat_model.md'
- API Reference: "docs/resources/bastionlab/index.html"
- Advanced:
  - Benchmarks:
    - Polars : 'docs/reference-guides/benchmarks/benchmarks.md'
    - Torch :
      - AMD EPY 7763: 'docs/reference-guides/benchmarks/Torch/bench-amd-epyc-7763.md'
      - NVIDIA A100/v100: 'docs/reference-guides/benchmarks/Torch/bench-nvidia-a100-v100.md'
- Contributing: 
  - 'docs/contributing/CONTRIBUTING.md'
  - Code of Conduct: 'docs/contributing/CODE_OF_CONDUCT.md'
