[package]
name = "bastionlab_learning"
version = "0.3.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.10.1"
torch-sys = "0.10.0"
libc = "0.2.126"
rand = "0.8.5"
