name: Publish to Docker Hub
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Free space
      - name: Free up space
        run: |
          curl https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash

      # Login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bastionlab:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/bastionlab:${{ github.event.release.tag_name }}

      # Build
      - name: Build and push Dockerfile.gpu.sev
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile.gpu.sev
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bastionlab-gpu:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/bastionlab-gpu:${{ github.event.release.tag_name }}
