name: Test notebook

on:
  pull_request:
    branches: [ master ]
    paths: ['client/**', 'server/**', '.github/**', 'docs/**']

jobs:
  testing_notebook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - serverImage: bastionlab
            os: ubuntu-latest
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      ########## SETUP ##########
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install utilities
        run: |
          pip install jupyter nbconvert

      ######### INSTALL CLIENT FROM SOURCE OTHERWISE ##########
      - name: Install bastionlab client from source
        run: |
          cd client
          make dev-install
          source env/bin/activate

      ##### BUILD SERVER OTHERWISE ######
      - name: Build server
        id: build-server-no-download
        run: |
          docker build -t ${{ matrix.serverImage }}:latest -f ./Dockerfile .

      ##### CHECK BASTIONLAB IMAGE IS INSTALLED ######
      - name: Check bastionlab image is installed
        id: check-bastionlab-image
        run: |
          docker image ls -a
          docker image inspect ${{ matrix.serverImage }}:latest

      ########## LAUNCH SERVER ##########
      - name: Launch server
        run: |
          docker kill -f app > /dev/null 2>&1 || true
          docker run --rm -d -e BASTIONLAB_DISABLE_TELEMETRY=1 -e DISABLE_AUTHENTICATION=1 -p 50056:50056  --name app ${{ matrix.serverImage }}:latest
      
      ########## TESTING NOTEBOOK ##########
      - name: Testing the notebooks
        run: |
          pip install ./client
          pip install jupyter nbconvert
          bash .github/scripts/test_notebooks.sh
